-- 아래는 GYM_MEMBER 테이블에 대한 구조를 보여줍니다. 테이블을 수정하실 필요는 없습니다.
DESC GYM_MEMBER;

-- 스쿼트 점수, 벤치 프레스 점수, 데드 리프트 점수의 합계에 대해 동일 점수는 같은 순위로 취급하여 순위를 매겨 조회하세요.
-- ORDER BY 컬럼 DESC: 내림차순 정렬

SELECT 
MEMBER_ID, 
SQUAT, 
BENCH_PRESS, 
DEADLIFT, 
(SQUAT+BENCH_PRESS+DEADLIFT) AS WEIGHT_SUM,
RANK() OVER (ORDER BY (SQUAT+BENCH_PRESS+DEADLIFT) DESC) AS 'RANK'
FROM GYM_MEMBER;












--DATA
CREATE TABLE GYM_MEMBER(
	MEMBER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SQUAT INTEGER,
	BENCH_PRESS INTEGER,
	DEADLIFT INTEGER
) AUTO_INCREMENT = 1;

INSERT INTO GYM_MEMBER(SQUAT, BENCH_PRESS, DEADLIFT) VALUES(110, 90, 80);
INSERT INTO GYM_MEMBER(SQUAT, BENCH_PRESS, DEADLIFT) VALUES(40, 40, 20);
INSERT INTO GYM_MEMBER(SQUAT, BENCH_PRESS, DEADLIFT) VALUES(250, 250, 180);
INSERT INTO GYM_MEMBER(SQUAT, BENCH_PRESS, DEADLIFT) VALUES(330, 210, 140);
INSERT INTO GYM_MEMBER(SQUAT, BENCH_PRESS, DEADLIFT) VALUES(5, 5, 5);
INSERT INTO GYM_MEMBER(SQUAT, BENCH_PRESS, DEADLIFT) VALUES(330, 350, 310);