-- 아래는 BOOK_HISTORY 테이블에 대한 구조를 보여줍니다. 테이블을 수정하실 필요는 없습니다.
DESC BOOK_HISTORY;

-- 책 종류와 책 카테고리로 그룹화 하고 ROLLUP을 이용하여 각 그룹당 판매 개수 합을 구해보세요.
SELECT 
KIND, CATEGORY, SUM(SELL_COUNT) AS TOTAL_SELL
FROM BOOK_HISTORY
GROUP BY KIND, CATEGORY WITH ROLLUP;




--DATA
CREATE TABLE BOOK_HISTORY(
	BOOK_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	BOOK_NAME VARCHAR(100),
	KIND VARCHAR(100),
	CATEGORY VARCHAR(100),
	SELL_COUNT INTEGER
);

INSERT INTO BOOK_HISTORY VALUES
(1001, 'SQL', 'PAPER BOOK', 'DEV', 10),
(1002, 'PASTA', 'PAPER BOOK', 'COOK', 1),
(1003, 'KOREA', 'E BOOK', 'CULTURE', 3),
(1004, 'JAVA', 'E BOOK', 'DEV', 5),
(1005, 'DATA', 'PAPER BOOK', 'DEV', 2),
(1006, 'SALAD', 'E BOOK', 'COOK', 5),
(1007, 'PIZZA', 'PAPER BOOK', 'COOK', 7),
(1008, 'JAPAN', 'E BOOK', 'CULTURE', 1),
(1009, 'PYTHON', 'E BOOK', 'DEV', 11),
(1010, 'BREAD', 'E BOOK', 'COOK', 8),
(1011, 'CHINA', 'PAPER BOOK', 'CULTURE', 2);